# Generated by Django 4.0.1 on 2022-02-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='track',
        ),
    ]
